services:
  - type: web
    name: pokemon-expense-tracker-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: static
    name: pokemon-expense-tracker-web
    rootDir: client
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://pokemon-expense-tracker-1.onrender.com/api
